CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522024403_InitialCreate') THEN
    CREATE TABLE "LicenseKeys" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(64) NOT NULL,
        "ClientName" character varying(200) NOT NULL,
        "Notes" text,
        "PlanName" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "LastValidatedAt" timestamp with time zone,
        CONSTRAINT "PK_LicenseKeys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522024403_InitialCreate') THEN
    CREATE TABLE "SessionTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Token" character varying(128) NOT NULL,
        "ClientName" character varying(200) NOT NULL,
        "IssuedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SessionTokens" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522024403_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LicenseKeys_Key" ON "LicenseKeys" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522024403_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SessionTokens_Token" ON "SessionTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522024403_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522024403_InitialCreate', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611010521_AddAdminKeys') THEN
    CREATE TABLE "AdminKeys" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(64) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AdminKeys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611010521_AddAdminKeys') THEN
    CREATE UNIQUE INDEX "IX_AdminKeys_Key" ON "AdminKeys" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611010521_AddAdminKeys') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611010521_AddAdminKeys', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611231407_AddPlans') THEN
    ALTER TABLE "LicenseKeys" ADD "PlanId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611231407_AddPlans') THEN
    CREATE TABLE "Plans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Price" numeric(10,2) NOT NULL,
        "MaxEmailsPerDay" integer,
        "DurationDays" integer,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Plans" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611231407_AddPlans') THEN
    CREATE INDEX "IX_LicenseKeys_PlanId" ON "LicenseKeys" ("PlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611231407_AddPlans') THEN
    CREATE UNIQUE INDEX "IX_Plans_Name" ON "Plans" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611231407_AddPlans') THEN
    ALTER TABLE "LicenseKeys" ADD CONSTRAINT "FK_LicenseKeys_Plans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "Plans" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611231407_AddPlans') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611231407_AddPlans', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611233850_AddDailyUsage') THEN
    CREATE TABLE "DailyUsages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LicenseKeyId" integer NOT NULL,
        "Date" date NOT NULL,
        "Operation" character varying(50) NOT NULL,
        "Count" integer NOT NULL,
        CONSTRAINT "PK_DailyUsages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DailyUsages_LicenseKeys_LicenseKeyId" FOREIGN KEY ("LicenseKeyId") REFERENCES "LicenseKeys" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611233850_AddDailyUsage') THEN
    CREATE UNIQUE INDEX "IX_DailyUsages_LicenseKeyId_Date_Operation" ON "DailyUsages" ("LicenseKeyId", "Date", "Operation");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611233850_AddDailyUsage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611233850_AddDailyUsage', '10.0.9');
    END IF;
END $EF$;
COMMIT;

